#!/bin/bash

orijs=./testOri.js
sourceAddr=$1
host=$2
port=$3
rm ./temp/mid1.js ./temp/mid2.js truffle-config.js
sed 's/.*from:.*/      from:\"'$sourceAddr'\",/g'  $orijs|cat >> ./temp/mid1.js
sed 's/.*host:.*/      host:\"'$host'\",/g' ./temp/mid1.js|cat >> ./temp/mid2.js
sed 's/.*port:.*/      port:'$port',/g' ./temp/mid2.js|cat >> truffle-config.js
